 version: '3.3'

 services:
   # Postgres
   db:
     image: postgres
     environment:
       - POSTGRES_USER=django_boards
       - POSTGRES_PASSWORD=django_boards
       - POSTGRES_DB=django_boards

   web:
     build: .
     command: ["./run_web.sh"]
     volumes:
       - .:/webapps
     ports:
       - "8000:8000"
     links:
       - db
     depends_on:
       - db
