version: '3.8'

services:
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64

  web:
    build: .
    command: ["/webapps/run_web.sh"]
    environment:
      MEMCACHED_HOST: cache
    volumes:
      - .:/webapps
    ports:
      - "8000:8000"
    links:
      - cache
    depends_on:
      - cache

volumes:
  db:
    driver: local