# Generated by Django 2.0.2 on 2018-03-14 04:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("punkweb_boards", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="boardprofile",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True
            ),
        )
    ]
