# Generated by Django 3.2.8 on 2021-11-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("punkweb_boards", "0002_boardprofile_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardprofile",
            name="metadata",
        ),
    ]
