# Generated by Django 4.0.1 on 2022-02-19 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('punkweb_boards', '0002_boardprofile_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardprofile',
            name='metadata',
        ),
        migrations.AlterField(
            model_name='boardprofile',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardprofile',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_upvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_upvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
